[package]
name = "mk_rss"
version = "1.0.1"
authors = [ "Jake Woods <jake@jakewoods.net>" ]
edition = "2018"

[dependencies]
anyhow = "1.0.31"
chrono = "0.4.15"
indoc = "1.0"
scraper = "0.12.0"
reqwest = "0.11"
